/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Volatility = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const SlotCategory = IDL.Variant({
  'megaways' : IDL.Null,
  'video' : IDL.Null,
  'classic' : IDL.Null,
  'progressive' : IDL.Null,
});
export const SlotReviewInput = IDL.Record({
  'rtp' : IDL.Float64,
  'screenshotUrls' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'features' : IDL.Text,
  'volatility' : Volatility,
  'cons' : IDL.Vec(IDL.Text),
  'pros' : IDL.Vec(IDL.Text),
  'overview' : IDL.Text,
  'minBet' : IDL.Float64,
  'description' : IDL.Text,
  'verdict' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'featuredImageUrl' : IDL.Text,
  'category' : SlotCategory,
  'rating' : IDL.Float64,
  'maxBet' : IDL.Float64,
  'gameplay' : IDL.Text,
  'videoUrl' : IDL.Opt(IDL.Text),
  'developer' : IDL.Text,
});
export const SlotReview = IDL.Record({
  'id' : IDL.Nat,
  'rtp' : IDL.Float64,
  'screenshotUrls' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'features' : IDL.Text,
  'volatility' : Volatility,
  'cons' : IDL.Vec(IDL.Text),
  'pros' : IDL.Vec(IDL.Text),
  'overview' : IDL.Text,
  'minBet' : IDL.Float64,
  'description' : IDL.Text,
  'verdict' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'featuredImageUrl' : IDL.Text,
  'category' : SlotCategory,
  'rating' : IDL.Float64,
  'maxBet' : IDL.Float64,
  'gameplay' : IDL.Text,
  'videoUrl' : IDL.Opt(IDL.Text),
  'dateAdded' : IDL.Int,
  'developer' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSlotReview' : IDL.Func([SlotReviewInput], [IDL.Nat], []),
  'deleteSlotReview' : IDL.Func([IDL.Nat], [], []),
  'getAllSlotReviews' : IDL.Func([], [IDL.Vec(SlotReview)], ['query']),
  'getFeaturedReviews' : IDL.Func([], [IDL.Vec(SlotReview)], ['query']),
  'getReviewsByCategory' : IDL.Func(
      [SlotCategory],
      [IDL.Vec(SlotReview)],
      ['query'],
    ),
  'getReviewsByRatingRange' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(SlotReview)],
      ['query'],
    ),
  'getReviewsByRtpRange' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(SlotReview)],
      ['query'],
    ),
  'getReviewsByVolatility' : IDL.Func(
      [Volatility],
      [IDL.Vec(SlotReview)],
      ['query'],
    ),
  'getSlotReview' : IDL.Func([IDL.Nat], [IDL.Opt(SlotReview)], ['query']),
  'updateSlotReview' : IDL.Func([IDL.Nat, SlotReviewInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Volatility = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const SlotCategory = IDL.Variant({
    'megaways' : IDL.Null,
    'video' : IDL.Null,
    'classic' : IDL.Null,
    'progressive' : IDL.Null,
  });
  const SlotReviewInput = IDL.Record({
    'rtp' : IDL.Float64,
    'screenshotUrls' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'features' : IDL.Text,
    'volatility' : Volatility,
    'cons' : IDL.Vec(IDL.Text),
    'pros' : IDL.Vec(IDL.Text),
    'overview' : IDL.Text,
    'minBet' : IDL.Float64,
    'description' : IDL.Text,
    'verdict' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'featuredImageUrl' : IDL.Text,
    'category' : SlotCategory,
    'rating' : IDL.Float64,
    'maxBet' : IDL.Float64,
    'gameplay' : IDL.Text,
    'videoUrl' : IDL.Opt(IDL.Text),
    'developer' : IDL.Text,
  });
  const SlotReview = IDL.Record({
    'id' : IDL.Nat,
    'rtp' : IDL.Float64,
    'screenshotUrls' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'features' : IDL.Text,
    'volatility' : Volatility,
    'cons' : IDL.Vec(IDL.Text),
    'pros' : IDL.Vec(IDL.Text),
    'overview' : IDL.Text,
    'minBet' : IDL.Float64,
    'description' : IDL.Text,
    'verdict' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'featuredImageUrl' : IDL.Text,
    'category' : SlotCategory,
    'rating' : IDL.Float64,
    'maxBet' : IDL.Float64,
    'gameplay' : IDL.Text,
    'videoUrl' : IDL.Opt(IDL.Text),
    'dateAdded' : IDL.Int,
    'developer' : IDL.Text,
  });
  
  return IDL.Service({
    'addSlotReview' : IDL.Func([SlotReviewInput], [IDL.Nat], []),
    'deleteSlotReview' : IDL.Func([IDL.Nat], [], []),
    'getAllSlotReviews' : IDL.Func([], [IDL.Vec(SlotReview)], ['query']),
    'getFeaturedReviews' : IDL.Func([], [IDL.Vec(SlotReview)], ['query']),
    'getReviewsByCategory' : IDL.Func(
        [SlotCategory],
        [IDL.Vec(SlotReview)],
        ['query'],
      ),
    'getReviewsByRatingRange' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(SlotReview)],
        ['query'],
      ),
    'getReviewsByRtpRange' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(SlotReview)],
        ['query'],
      ),
    'getReviewsByVolatility' : IDL.Func(
        [Volatility],
        [IDL.Vec(SlotReview)],
        ['query'],
      ),
    'getSlotReview' : IDL.Func([IDL.Nat], [IDL.Opt(SlotReview)], ['query']),
    'updateSlotReview' : IDL.Func([IDL.Nat, SlotReviewInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };