/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type SlotCategory = { 'megaways' : null } |
  { 'video' : null } |
  { 'classic' : null } |
  { 'progressive' : null };
export interface SlotReview {
  'id' : bigint,
  'rtp' : number,
  'screenshotUrls' : Array<string>,
  'title' : string,
  'features' : string,
  'volatility' : Volatility,
  'cons' : Array<string>,
  'pros' : Array<string>,
  'overview' : string,
  'minBet' : number,
  'description' : string,
  'verdict' : string,
  'isFeatured' : boolean,
  'featuredImageUrl' : string,
  'category' : SlotCategory,
  'rating' : number,
  'maxBet' : number,
  'gameplay' : string,
  'videoUrl' : [] | [string],
  'dateAdded' : bigint,
  'developer' : string,
}
export interface SlotReviewInput {
  'rtp' : number,
  'screenshotUrls' : Array<string>,
  'title' : string,
  'features' : string,
  'volatility' : Volatility,
  'cons' : Array<string>,
  'pros' : Array<string>,
  'overview' : string,
  'minBet' : number,
  'description' : string,
  'verdict' : string,
  'isFeatured' : boolean,
  'featuredImageUrl' : string,
  'category' : SlotCategory,
  'rating' : number,
  'maxBet' : number,
  'gameplay' : string,
  'videoUrl' : [] | [string],
  'developer' : string,
}
export type Volatility = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface _SERVICE {
  'addSlotReview' : ActorMethod<[SlotReviewInput], bigint>,
  'deleteSlotReview' : ActorMethod<[bigint], undefined>,
  'getAllSlotReviews' : ActorMethod<[], Array<SlotReview>>,
  'getFeaturedReviews' : ActorMethod<[], Array<SlotReview>>,
  'getReviewsByCategory' : ActorMethod<[SlotCategory], Array<SlotReview>>,
  'getReviewsByRatingRange' : ActorMethod<[number, number], Array<SlotReview>>,
  'getReviewsByRtpRange' : ActorMethod<[number, number], Array<SlotReview>>,
  'getReviewsByVolatility' : ActorMethod<[Volatility], Array<SlotReview>>,
  'getSlotReview' : ActorMethod<[bigint], [] | [SlotReview]>,
  'updateSlotReview' : ActorMethod<[bigint, SlotReviewInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];