/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SlotReviewInput {
    rtp: number;
    screenshotUrls: Array<string>;
    title: string;
    features: string;
    volatility: Volatility;
    cons: Array<string>;
    pros: Array<string>;
    overview: string;
    minBet: number;
    description: string;
    verdict: string;
    isFeatured: boolean;
    featuredImageUrl: string;
    category: SlotCategory;
    rating: number;
    maxBet: number;
    gameplay: string;
    videoUrl?: string;
    developer: string;
}
export interface SlotReview {
    id: bigint;
    rtp: number;
    screenshotUrls: Array<string>;
    title: string;
    features: string;
    volatility: Volatility;
    cons: Array<string>;
    pros: Array<string>;
    overview: string;
    minBet: number;
    description: string;
    verdict: string;
    isFeatured: boolean;
    featuredImageUrl: string;
    category: SlotCategory;
    rating: number;
    maxBet: number;
    gameplay: string;
    videoUrl?: string;
    dateAdded: bigint;
    developer: string;
}
export enum SlotCategory {
    megaways = "megaways",
    video = "video",
    classic = "classic",
    progressive = "progressive"
}
export enum Volatility {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    addSlotReview(input: SlotReviewInput): Promise<bigint>;
    deleteSlotReview(id: bigint): Promise<void>;
    getAllSlotReviews(): Promise<Array<SlotReview>>;
    getFeaturedReviews(): Promise<Array<SlotReview>>;
    getReviewsByCategory(category: SlotCategory): Promise<Array<SlotReview>>;
    getReviewsByRatingRange(minRating: number, maxRating: number): Promise<Array<SlotReview>>;
    getReviewsByRtpRange(minRtp: number, maxRtp: number): Promise<Array<SlotReview>>;
    getReviewsByVolatility(volatility: Volatility): Promise<Array<SlotReview>>;
    getSlotReview(id: bigint): Promise<SlotReview | null>;
    updateSlotReview(id: bigint, input: SlotReviewInput): Promise<void>;
}
import type { SlotCategory as _SlotCategory, SlotReview as _SlotReview, SlotReviewInput as _SlotReviewInput, Volatility as _Volatility } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSlotReview(arg0: SlotReviewInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSlotReview(to_candid_SlotReviewInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSlotReview(to_candid_SlotReviewInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteSlotReview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSlotReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSlotReview(arg0);
            return result;
        }
    }
    async getAllSlotReviews(): Promise<Array<SlotReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSlotReviews();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSlotReviews();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedReviews(): Promise<Array<SlotReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedReviews();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedReviews();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsByCategory(arg0: SlotCategory): Promise<Array<SlotReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByCategory(to_candid_SlotCategory_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByCategory(to_candid_SlotCategory_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsByRatingRange(arg0: number, arg1: number): Promise<Array<SlotReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByRatingRange(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByRatingRange(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsByRtpRange(arg0: number, arg1: number): Promise<Array<SlotReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByRtpRange(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByRtpRange(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsByVolatility(arg0: Volatility): Promise<Array<SlotReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByVolatility(to_candid_Volatility_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByVolatility(to_candid_Volatility_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSlotReview(arg0: bigint): Promise<SlotReview | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSlotReview(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSlotReview(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSlotReview(arg0: bigint, arg1: SlotReviewInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSlotReview(arg0, to_candid_SlotReviewInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSlotReview(arg0, to_candid_SlotReviewInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_SlotCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SlotCategory): SlotCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SlotReview_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SlotReview): SlotReview {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Volatility_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Volatility): Volatility {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SlotReview]): SlotReview | null {
    return value.length === 0 ? null : from_candid_SlotReview_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    rtp: number;
    screenshotUrls: Array<string>;
    title: string;
    features: string;
    volatility: _Volatility;
    cons: Array<string>;
    pros: Array<string>;
    overview: string;
    minBet: number;
    description: string;
    verdict: string;
    isFeatured: boolean;
    featuredImageUrl: string;
    category: _SlotCategory;
    rating: number;
    maxBet: number;
    gameplay: string;
    videoUrl: [] | [string];
    dateAdded: bigint;
    developer: string;
}): {
    id: bigint;
    rtp: number;
    screenshotUrls: Array<string>;
    title: string;
    features: string;
    volatility: Volatility;
    cons: Array<string>;
    pros: Array<string>;
    overview: string;
    minBet: number;
    description: string;
    verdict: string;
    isFeatured: boolean;
    featuredImageUrl: string;
    category: SlotCategory;
    rating: number;
    maxBet: number;
    gameplay: string;
    videoUrl?: string;
    dateAdded: bigint;
    developer: string;
} {
    return {
        id: value.id,
        rtp: value.rtp,
        screenshotUrls: value.screenshotUrls,
        title: value.title,
        features: value.features,
        volatility: from_candid_Volatility_n10(_uploadFile, _downloadFile, value.volatility),
        cons: value.cons,
        pros: value.pros,
        overview: value.overview,
        minBet: value.minBet,
        description: value.description,
        verdict: value.verdict,
        isFeatured: value.isFeatured,
        featuredImageUrl: value.featuredImageUrl,
        category: from_candid_SlotCategory_n12(_uploadFile, _downloadFile, value.category),
        rating: value.rating,
        maxBet: value.maxBet,
        gameplay: value.gameplay,
        videoUrl: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.videoUrl)),
        dateAdded: value.dateAdded,
        developer: value.developer
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Volatility {
    return "low" in value ? Volatility.low : "high" in value ? Volatility.high : "medium" in value ? Volatility.medium : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    megaways: null;
} | {
    video: null;
} | {
    classic: null;
} | {
    progressive: null;
}): SlotCategory {
    return "megaways" in value ? SlotCategory.megaways : "video" in value ? SlotCategory.video : "classic" in value ? SlotCategory.classic : "progressive" in value ? SlotCategory.progressive : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SlotReview>): Array<SlotReview> {
    return value.map((x)=>from_candid_SlotReview_n8(_uploadFile, _downloadFile, x));
}
function to_candid_SlotCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SlotCategory): _SlotCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SlotReviewInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SlotReviewInput): _SlotReviewInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Volatility_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Volatility): _Volatility {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rtp: number;
    screenshotUrls: Array<string>;
    title: string;
    features: string;
    volatility: Volatility;
    cons: Array<string>;
    pros: Array<string>;
    overview: string;
    minBet: number;
    description: string;
    verdict: string;
    isFeatured: boolean;
    featuredImageUrl: string;
    category: SlotCategory;
    rating: number;
    maxBet: number;
    gameplay: string;
    videoUrl?: string;
    developer: string;
}): {
    rtp: number;
    screenshotUrls: Array<string>;
    title: string;
    features: string;
    volatility: _Volatility;
    cons: Array<string>;
    pros: Array<string>;
    overview: string;
    minBet: number;
    description: string;
    verdict: string;
    isFeatured: boolean;
    featuredImageUrl: string;
    category: _SlotCategory;
    rating: number;
    maxBet: number;
    gameplay: string;
    videoUrl: [] | [string];
    developer: string;
} {
    return {
        rtp: value.rtp,
        screenshotUrls: value.screenshotUrls,
        title: value.title,
        features: value.features,
        volatility: to_candid_Volatility_n3(_uploadFile, _downloadFile, value.volatility),
        cons: value.cons,
        pros: value.pros,
        overview: value.overview,
        minBet: value.minBet,
        description: value.description,
        verdict: value.verdict,
        isFeatured: value.isFeatured,
        featuredImageUrl: value.featuredImageUrl,
        category: to_candid_SlotCategory_n5(_uploadFile, _downloadFile, value.category),
        rating: value.rating,
        maxBet: value.maxBet,
        gameplay: value.gameplay,
        videoUrl: value.videoUrl ? candid_some(value.videoUrl) : candid_none(),
        developer: value.developer
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Volatility): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Volatility.low ? {
        low: null
    } : value == Volatility.high ? {
        high: null
    } : value == Volatility.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SlotCategory): {
    megaways: null;
} | {
    video: null;
} | {
    classic: null;
} | {
    progressive: null;
} {
    return value == SlotCategory.megaways ? {
        megaways: null
    } : value == SlotCategory.video ? {
        video: null
    } : value == SlotCategory.classic ? {
        classic: null
    } : value == SlotCategory.progressive ? {
        progressive: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
